name: Generate C4 Diagrams

on:
  push:
    paths:
      - diagrams/**/*.puml
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup PlantUML
        uses: plantuml/plantuml-action@v1.5.0

      - name: Generate PNG diagrams
        run: |
          mkdir -p output
          for file in diagrams/*.puml; do
            plantuml -tpng "$file" -o ./output
          done

      - name: Commit and push diagrams
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git pull --rebase
          git add output/*.png || true
          git commit -m "Update diagrams [skip ci]" || echo "No changes to commit"
          git remote set-url origin https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }}
          git push origin HEAD
