name: Generate and Commit C4 Diagrams

on:
  push:
    paths:
      - diagrams/**/*.puml
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install PlantUML
        run: sudo apt-get install -y plantuml

      - name: Generate Diagrams
        run: |
          mkdir -p output
          for file in diagrams/*.puml; do
            plantuml -tpng "$file" -o output/
          done

      - name: Commit and Push Diagrams
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git pull --rebase
          git add output/*.png || true
          git commit -m "Add generated diagrams [skip ci]" || echo "No changes"
          git push
